name: Release
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

# Define PORTAL_DOMAIN env for website deploy
env:
  PORTAL_DOMAIN: siasky.net

jobs:
  # Run the linting and tests
  hadolint:
    uses: SkynetLabs/.github/.github/workflows/reusable_dockerfile_lint.yml@master

  check:
    name: "Checks and Tests"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: "Run Yarn Basic Checks"
        uses: SkynetLabs/.github/.github/actions/yarn-basic-checks@master
        with:
          node-version: ${{ matrix.node-version }}

  deploy:
    name: "Deploy Website to Skynet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn
      - run: yarn build

      - name: "Integration tests"
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: false
          record: true
          start: yarn develop
          wait-on: http://localhost:8000
          wait-on-timeout: 120
          config: baseUrl=http://localhost:8000

      - name: "Deploy to Skynet"
        uses: skynetlabs/deploy-to-skynet-action@v2
        with:
          upload-dir: public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.WEBSITE_REGISTRY_SEED || '' }}

  # Make a release if this is a manually trigger job, i.e. workflow_dispatch
  release:
    needs: [hadolint, check, deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    outputs:
      new_version: ${{ steps.version.outputs.new-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Version Release
        id: version
        uses: SkynetLabs/.github/.github/actions/version-release@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          version-bump: ${{github.event.inputs.version}}

  docker:
    needs: release
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: SkynetLabs/.github/.github/actions/docker-publish@master
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME}}
          docker_password: ${{ secrets.DOCKER_PASSWORD}}
          docker_repository: skynetlabs/webportal-website
          semver_version: ${{ needs.release.outputs.new_version }}
